name: lost
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  multi_image_picker:
  http:
  provider:
  flutter_colorpicker:
  intl:
  carousel_slider :
  path_provider:
  flutter_absolute_path:
  splashscreen:
  firebase_core: ^1.4.0
  firebase_database: ^7.1.2
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  file_picker: ^3.0.4
  image_picker: ^0.8.2
  permission_handler: ^8.1.4+2
  firebase_storage: ^10.0.1
  camera: ^0.8.1+7
  fluttertoast: ^8.0.7
  toast: ^0.1.5
  page_transition: ^2.0.2
  slide_popup_dialog: ^0.0.2
  curved_navigation_bar: ^1.0.1
  share: ^2.0.4
  firebase_dynamic_links: ^2.0.9
  url_launcher: ^6.0.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon_1.jpg"

flutter:
  uses-material-design: true
  assets:
    - images/
